version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Install Google Java Format
          command: |
            curl -LJO "https://github.com/google/google-java-format/releases/download/v1.15.0/google-java-format-1.15.0-all-deps.jar"
      - run:
          name: Check Code Format
          command: java -jar google-java-format-1.15.0-all-deps.jar --set-exit-if-changed -n $(find . -name "*.java")
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  build-and-test:
    jobs:
      - build-and-test
